# Generated by Django 6.0.3 on 2026-03-28 07:02

import django.db.models.deletion
import recognition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[recognition.models.validate_jss_email])),
                ('class_section', models.CharField(choices=[('IT 1', 'Information Technology - Section 1'), ('IT 2', 'Information Technology - Section 2'), ('IT 3', 'Information Technology - Section 3')], max_length=10)),
                ('photo', models.ImageField(upload_to='student_photos/')),
                ('encoding', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognition.student')),
            ],
        ),
    ]
